### PR TITLE
Readme Upload Support

### PR DESCRIPTION
**Pull request by C-Loftus**
# Description

Allow submitting or updating the single readme for a namespace when submitting a single csv 

# Changes Made

Commits a readme file by extracting the data from a form. 

## Future Work

- Create a tooltip / help button for users to see the proper format for formatting their inputs
- Improve markdown formatting so that the links are rendered as links after submitting or 
- Form validation to make sure the link is a valid url and the email is a valid email
    - (Only after this can we render the parsed text into links since otherwise we can't be sure the links they submit are actually valid links anyways)

# Additional Notes

Test commit: https://github.com/webb-ben/geoconnex.us/pull/42

_screenshot zoomed out_
image

### CODE REVIEW

**Comment by ksonda** [comment]
Great work!

Suggestion:

Include a link to a csv template example they can download to replace/fill out, one for 1:1 matches and one for regex. pretty simple, the fields are just `id`, `target`, `creator`, `description`

an example for 1:1 could be https://github.com/internetofwater/geoconnex.us/blob/master/namespaces/SELFIE/SELFIE_ids.csv

an example for regex could be https://github.com/internetofwater/geoconnex.us/blob/master/namespaces/usgs/monitoring-location/monitoring-location.csv

**Comment by ksonda** [comment]
Suggestion:

Change title to "Register Persistent Identifiers for Geoconnex"

Include some introductory text under the title. "Use for the form below to submit a csv file that will register persistent URL-formatted identifiers for your organization's monitoring locations within a "namespace" (short name for your organization). Please fill out all fields to ensure that Geoconnex administrators can ensure your identifiers are well-documented and can follow up with you if there are any issues."

Change "Metadata for your README" to "Contribution Information"

Maybe all fields can have example text in them if nothing is typed in, like for namspace "e.g. usgs", and the other examples I put in #6 


Change "documentation" button to "Click for Detailed Contribution Documentation"

**Comment by C-Loftus** [comment]
@ksonda Thanks for your feedback. I made those changes. Here is what I did and some motivations for design

- I made the example hints show always below the text field. I was worried that if it was sample text, they might forget the format or add friction as they are filling in the info due to it not being visible
- I added the drop down with the CSV links from #6  The drop down has slightly different styling to emphasize it isn't part of the form. I put relatively limited info in this since I figured it is probably best for them to view the detailed documentation at the bottom.
    - I can add csv column validation at some point as well if desired.
- I changed the title and details after it

Here are some screenshots. I will probably add branch previews / do a netlify integration at some point so it is easier to review without needing to clone/run/look at a picture

image
image

**Comment by C-Loftus** [comment]
Oh and I assumed that using the usgs info as the example would be ok, but if not, please let me know and Ill change it. I figured a live example is more useful than me mimicking the format with a dummy url.

**Comment by ksonda** [comment]
Looks good!

**Pull request merged**
