### PR TITLE
CSV validation with associated testing

### PR DESCRIPTION
**Pull request by C-Loftus**
# Description

Adds tests for the CSVs for register.geoconnex.us. This is done all on the frontend so it is not checking that the ids are unique when compared to other ids in geoconnex. This is a first step and can be iterated if desired going forward. 

You can see all the cases we handle by checking the helpers.test.ts file. It is generally checking to make sure that there is are the proper columns, and that each column is of the proper type.

Checks to make sure the URLs in the target column are valid

image
image
image

It is not checking all the edge cases within regex identifiers.

### CODE REVIEW

**Comment by webb-ben** [comment]
Just to confirm this is primarily testing the columns? Am I correct that we are only validating the header and first row in the CSV?

**Comment by C-Loftus** [comment]
> Just to confirm this is primarily testing the columns? Am I correct that we are only validating the header and first row in the CSV?

Correct. I can definitely go through the entire CSV and validate every item in every row though as well if you would like. That is straightforward to implement, just don't want to slow down the frontend if there is a huge file. Although perhaps that isn't likely to be an issue?

I am happy to implement whatever you think is best. Please let me know what you prefer.

**Comment by webb-ben** [comment]
Well there had been some conversation of making sure the target urls return an acceptable HTTP status. Is there a way to test the targets in bulk relatively efficiently?

That being said I have to imagine it would take a while to validate 299,999 target URLs and no way to test regex based identifiers.

**Comment by C-Loftus** [comment]
Sure I can use [promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) to make a many requests in parallel. It will obviously slow things down a bit but I can add another spinner for UX to signify the different steps of the check process

**Comment by C-Loftus** [comment]
Quick question, how should I be testing targets which contain regex mappings? Do I just make sure the domain is valid? Since it isn't possible to test every possible regex match right? Or should I just skip any regexes? 

Speaking of which I am seeing that the 1:1 example itself contains a regex. And the 1:N has another regex for determining the c_1 / c_2 value match (Unless I have mixed things up) https://github.com/internetofwater/geoconnex.us/blob/master/namespaces/usgs/monitoring-location/monitoring-location.csv

Let me know what you think is feasible and worth the time

**Comment by webb-ben** [comment]
Not worth validating regex. The CSV files should be either 1:1 or 1:N but not mixed.

Only those 4 fields are currently required. The rest are from the early implementation and we mostly ignore them now.

**Comment by C-Loftus** [comment]
Added support for checking if the target URLs are valid or not. Added a few images to the PR. Should be ready to review.

I allow the user to override this check if there is some sort of edge case. However, we show a warning of all target URLs that failed before overriding.

**Review by webb-ben — APPROVED** [review]

**Pull request merged**
